// Generated by CoffeeScript 1.7.1
"use strict";
module.exports = function(grunt) {
  require("load-grunt-tasks")(grunt);
  require("time-grunt")(grunt);
  grunt.config.set("ip", require("ip").address());
  grunt.initConfig({
    yeoman: {
      app: require("./bower.json").appPath || "app",
      dist: "dist"
    },
    watch: {
      bower: {
        files: ["bower.json"],
        tasks: ["bowerInstall"]
      },
      js: {
        files: ["<%= yeoman.app %>/scripts/{,*/}*.js"],
        tasks: ["newer:jshint:all"],
        options: {
          livereload: true
        }
      },
      jsTest: {
        files: ["test/spec/{,*/}*.js"],
        tasks: ["newer:jshint:test", "karma"]
      },
      compass: {
        files: ["<%= yeoman.app %>/styles/{,*/}*.{scss,sass}"],
        tasks: ["compass:server", "autoprefixer"]
      },
      gruntfile: {
        files: ["Gruntfile.js"]
      },
      livereload: {
        options: {
          livereload: "<%= connect.options.livereload %>"
        },
        files: ["<%= yeoman.app %>/{,*/}*.html", ".tmp/styles/{,*/}*.css", "<%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}"]
      }
    },
    connect: {
      options: {
        port: 9000,
        hostname: grunt.config.get("ip"),
        livereload: 35729
      },
      livereload: {
        options: {
          open: true,
          base: [".tmp", "<%= yeoman.app %>"]
        }
      },
      test: {
        options: {
          port: 9001,
          base: [".tmp", "test", "<%= yeoman.app %>"]
        }
      },
      dist: {
        options: {
          open: true,
          base: "<%= yeoman.dist %>"
        }
      }
    },
    jshint: {
      options: {
        jshintrc: ".jshintrc",
        reporter: require("jshint-stylish")
      },
      all: ["Gruntfile.js", "<%= yeoman.app %>/scripts/{,*/}*.js"],
      test: {
        options: {
          jshintrc: "test/.jshintrc"
        },
        src: ["test/spec/{,*/}*.js"]
      }
    },
    clean: {
      dist: {
        files: [
          {
            dot: true,
            src: [".tmp", "<%= yeoman.dist %>/*", "!<%= yeoman.dist %>/.git*"]
          }
        ]
      },
      distView: {
        files: [
          {
            dot: true,
            src: ["<%= yeoman.dist %>/views"]
          }
        ]
      },
      server: ".tmp"
    },
    autoprefixer: {
      options: {
        browsers: ["last 1 version"]
      },
      dist: {
        files: [
          {
            expand: true,
            cwd: ".tmp/styles/",
            src: "{,*/}*.css",
            dest: ".tmp/styles/"
          }
        ]
      }
    },
    bowerInstall: {
      app: {
        src: ["<%= yeoman.app %>/index.html"],
        ignorePath: "<%= yeoman.app %>/"
      },
      sass: {
        src: ["<%= yeoman.app %>/styles/{,*/}*.{scss,sass}"],
        ignorePath: "<%= yeoman.app %>/bower_components/"
      }
    },
    compass: {
      options: {
        sassDir: "<%= yeoman.app %>/styles",
        cssDir: ".tmp/styles",
        generatedImagesDir: ".tmp/images/generated",
        imagesDir: "<%= yeoman.app %>/images",
        javascriptsDir: "<%= yeoman.app %>/scripts",
        fontsDir: "<%= yeoman.app %>/styles/fonts",
        importPath: "<%= yeoman.app %>/bower_components",
        httpImagesPath: "/images",
        httpGeneratedImagesPath: "/images/generated",
        httpFontsPath: "/styles/fonts",
        relativeAssets: false,
        assetCacheBuster: false,
        raw: "Sass::Script::Number.precision = 10\n"
      },
      dist: {
        options: {
          generatedImagesDir: "<%= yeoman.dist %>/images/generated"
        }
      },
      server: {
        options: {
          debugInfo: true
        }
      }
    },
    rev: {
      dist: {
        files: {
          src: ["<%= yeoman.dist %>/scripts/{,*/}*.js", "<%= yeoman.dist %>/styles/{,*/}*.css", "<%= yeoman.dist %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}", "<%= yeoman.dist %>/styles/fonts/*"]
        }
      }
    },
    useminPrepare: {
      html: "<%= yeoman.app %>/index.html",
      options: {
        dest: "<%= yeoman.dist %>",
        flow: {
          html: {
            steps: {
              js: ["concat", "uglifyjs"],
              css: ["cssmin"]
            },
            post: {}
          }
        }
      }
    },
    usemin: {
      html: ["<%= yeoman.dist %>/{,*/}*.html"],
      css: ["<%= yeoman.dist %>/styles/{,*/}*.css"],
      options: {
        assetsDirs: ["<%= yeoman.dist %>"]
      }
    },
    cssmin: {
      options: {
        root: "<%= yeoman.app %>"
      }
    },
    imagemin: {
      dist: {
        files: [
          {
            expand: true,
            cwd: "<%= yeoman.app %>/images",
            src: "{,*/}*.{png,jpg,jpeg,gif}",
            dest: "<%= yeoman.dist %>/images"
          }
        ]
      }
    },
    svgmin: {
      dist: {
        files: [
          {
            expand: true,
            cwd: "<%= yeoman.app %>/images",
            src: "{,*/}*.svg",
            dest: "<%= yeoman.dist %>/images"
          }
        ]
      }
    },
    htmlmin: {
      dist: {
        options: {
          collapseWhitespace: true,
          collapseBooleanAttributes: true,
          removeCommentsFromCDATA: true,
          removeOptionalTags: true,
          removeComments: true
        },
        files: [
          {
            expand: true,
            cwd: "<%= yeoman.dist %>",
            src: ["*.html"],
            dest: "<%= yeoman.dist %>"
          }
        ]
      }
    },
    ngmin: {
      dist: {
        files: [
          {
            expand: true,
            cwd: ".tmp/concat/scripts",
            src: "*.js",
            dest: ".tmp/concat/scripts"
          }
        ]
      }
    },
    cdnify: {
      dist: {
        html: ["<%= yeoman.dist %>/*.html"]
      }
    },
    copy: {
      dist: {
        files: [
          {
            expand: true,
            dot: true,
            cwd: "<%= yeoman.app %>",
            dest: "<%= yeoman.dist %>",
            src: ["*.{ico,png,txt}", ".htaccess", "*.html", "views/{,*/}*.html", "images/{,*/}*.{webp}", "fonts/*", "bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/*", "bower_components/es5-shim/es5-shim.min.js", "bower_components/json3/lib/json3.min.js", "data/*"]
          }, {
            expand: true,
            cwd: ".tmp/images",
            dest: "<%= yeoman.dist %>/images",
            src: ["generated/*"]
          }
        ]
      },
      styles: {
        expand: true,
        cwd: "<%= yeoman.app %>/styles",
        dest: ".tmp/styles/",
        src: "{,*/}*.css"
      }
    },
    concurrent: {
      server: ["compass:server"],
      test: ["compass"],
      dist: ["compass:dist", "imagemin", "svgmin"]
    },
    karma: {
      unit: {
        configFile: "karma.conf.js",
        singleRun: true
      }
    },
    "ng_template": {
      files: ["<%= yeoman.dist %>/views"],
      options: {
        appDir: "<%= yeoman.dist %>",
        indexFile: "index.html",
        concat: true
      }
    }
  });
  grunt.registerTask("serve", function(target) {
    if (target === "dist") {
      return grunt.task.run(["build", "connect:dist:keepalive"]);
    }
    grunt.task.run(["clean:server", "bowerInstall", "concurrent:server", "autoprefixer", "connect:livereload", "watch"]);
  });
  grunt.registerTask("server", function(target) {
    grunt.log.warn("The `server` task has been deprecated. Use `grunt serve` to start a server.");
    grunt.task.run(["serve:" + target]);
  });
  grunt.registerTask("test", ["clean:server", "concurrent:test", "autoprefixer", "connect:test", "karma"]);
  grunt.registerTask("build", ["clean:dist", "bowerInstall", "useminPrepare", "concurrent:dist", "autoprefixer", "concat", "ngmin", "copy:dist", "cdnify", "cssmin", "uglify", "rev", "usemin", "ng_template", "htmlmin", "clean:distView"]);
  return grunt.registerTask("default", ["newer:jshint", "test", "build"]);
};
