// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("aboutCtrl", function($scope, $http) {
  var about;
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "about");
  });
  about = {
    init: function() {
      return about.getAbout();
    },
    getAbout: function() {
      var api;
      api = "" + API.aboutsite + $scope.privacyParamDir + "?infokey=about";
      if (IsDebug) {
        api = API.aboutsite;
      }
      return $http.get(api, {
        cache: true
      }).success(about.getAboutCb);
    },
    getAboutCb: function(data) {
      var msg, result, ret;
      ret = data.ret, msg = data.msg, result = data.result;
      return $scope.site = result;
    }
  };
  about.init();
  return false;
});
