// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("globalCtrl", function($scope) {
  var BASE_API_PATH, BODY, DOC, IsAndroid, IsAndroidPad, IsBlackBerry, IsChrome, IsDebug, IsIE, IsIEMobile, IsIOS, IsIPad, IsIPhone, IsPhone, IsTouch, IsWeixin, IsWindowsPhone, LOC, NA, NG, UA, WIN;
  DOC = document;
  WIN = window;
  LOC = location;
  BODY = DOC['body'];

  /*
  设备是否支持触摸事件
  这里使用WIN.hasOwnProperty('ontouchend')在Android上会得到错误的结果
  @type {boolean}
   */
  IsTouch = "ontouchend" in WIN;
  NA = WIN.navigator;
  UA = NA.userAgent;
  IsAndroid = /Android|HTC/i.test(UA) || /Linux/i.test(NA.platform + "");
  IsAndroidPad = IsAndroid && /Pad/i.test(UA);
  IsIPad = !IsAndroid && /iPad/i.test(UA);
  IsIPhone = !IsAndroid && /iPod|iPhone/i.test(UA);
  IsIOS = IsIPad || IsIPhone;
  IsWindowsPhone = /Windows Phone/i.test(UA);
  IsBlackBerry = /BB10|BlackBerry/i.test(UA);
  IsIEMobile = /IEMobile/i.test(UA);
  IsIE = !!DOC.all;
  IsWeixin = /MicroMessenger/i.test(UA);
  IsChrome = !!WIN['chrome'];
  IsPhone = IsIPhone || (IsAndroid && !IsAndroidPad);
  NG = WIN['angular'];
  $scope.WIN = WIN;
  $scope.DOC = DOC;
  $scope.LOC = LOC;
  $scope.BODY = BODY;
  $scope.IsIPhone = IsIPhone;
  $scope.IsIPad = IsIPad;
  $scope.IsIOS = IsIOS;
  $scope.IsAndroid = IsAndroid;
  $scope.IsAndroidPad = IsAndroidPad;
  $scope.IsIEMobile = IsIEMobile;
  $scope.IsWeixin = IsWeixin;
  $scope.IsTouch = $scope.IsMobile = IsTouch;
  $scope.IsChrome = IsChrome;
  $scope.IsIE = IsIE;
  $scope.IsPhone = IsPhone;
  IsDebug = LOC["port"] === "9000";
  $scope.IsDebug = IsDebug;
  BASE_API_PATH = "/mifan/service/index.php";
  $scope.API = {
    user: "" + BASE_API_PATH + "/user/usersession/user",
    userInfo: "" + BASE_API_PATH + "/user/userinfo/user/id"
  };
  if (IsDebug) {
    BASE_API_PATH = "/data";
    $scope.API = {
      user: "" + BASE_API_PATH + "/user.json",
      userInfo: "" + BASE_API_PATH + "/user-info.json"
    };
  }
  return $scope.DEFAULT_FACE = "http://mifan.us/public/images/user_normal.jpg";
});
