// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("globalCtrl", function($scope) {
  var BODY, DOC, IsAndroid, IsBlackBerry, IsChrome, IsDebug, IsIE, IsIEMobile, IsIOS, IsIPad, IsIPhone, IsTouch, IsWeixin, IsWindowsPhone, LOC, NA, NG, UA, WIN;
  DOC = document;
  WIN = window;
  LOC = location;
  BODY = DOC['body'];

  /*
  设备是否支持触摸事件
  这里使用WIN.hasOwnProperty('ontouchend')在Android上会得到错误的结果
  @type {boolean}
   */
  IsTouch = "ontouchend" in WIN;
  NA = WIN.navigator;
  UA = NA.userAgent;
  IsAndroid = /Android|HTC/i.test(UA) || /Linux/i.test(NA.platform + "");
  IsIPad = !IsAndroid && /iPad/i.test(UA);
  IsIPhone = !IsAndroid && /iPod|iPhone/i.test(UA);
  IsIOS = IsIPad || IsIPhone;
  IsWindowsPhone = /Windows Phone/i.test(UA);
  IsBlackBerry = /BB10|BlackBerry/i.test(UA);
  IsIEMobile = /IEMobile/i.test(UA);
  IsIE = !!DOC.all;
  IsWeixin = /MicroMessenger/i.test(UA);
  IsChrome = !!WIN['chrome'];
  NG = WIN['angular'];
  $scope.WIN = WIN;
  $scope.DOC = DOC;
  $scope.LOC = LOC;
  $scope.BODY = BODY;
  $scope.IsIPhone = IsIPhone;
  $scope.IsIPad = IsIPad;
  $scope.IsIOS = IsIOS;
  $scope.IsAndroid = IsAndroid;
  $scope.IsIEMobile = IsIEMobile;
  $scope.IsWeixin = IsWeixin;
  $scope.IsTouch = $scope.IsMobile = IsTouch;
  $scope.IsChrome = IsChrome;
  $scope.IsIE = IsIE;
  $scope.UCNAME = "MifanUser";
  IsDebug = LOC["port"] === "9000";
  $scope.IsDebug = IsDebug;
  $scope.API = {
    user: "/mifan/service/index.php?/user/usersession/user"
  };
  if (IsDebug) {
    return $scope.API = {
      user: "/data/user.json"
    };
  }
});
