// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("headCtrl", function($scope) {
  $scope.currentPage = "home";
  $scope.username = "老婆婆";
  $scope.supportNum = "1万";
  $scope.isDropdownOpen = false;
  $scope.support = function() {
    return alert(1);
  };
  return false;
});
