// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("headCtrl", function($scope) {
  $scope.dropdownOpen = false;
  $scope.toggleDropdown = function() {
    return $scope.dropdownOpen = !$scope.dropdownOpen;
  };
  $scope.support = function() {
    return alert(1);
  };
  $scope.navs = [
    {
      page: "home",
      text: "首页"
    }, {
      page: "msg",
      text: "消息"
    }, {
      page: "me",
      text: "个人主页"
    }, {
      page: "friend",
      text: "朋友"
    }, {
      page: "hot",
      text: "排行"
    }
  ];
  $scope.remind = "米饭新增豆瓣登录!";
  return $scope.remind = "";
});
