// Generated by CoffeeScript 1.7.1
Mifan.controller("homeAnswer", function($scope) {
  var homeCtrlScope;
  $scope.content = "huidawode";
  console.log("huidawode");
  homeCtrlScope = angular.element('.home-page').scope();
  return homeCtrlScope.remind.answerNum = 0;
});
