// Generated by CoffeeScript 1.7.1
angular.module("mifan").controller("homeReply", function($scope) {
  var homeCtrlScope;
  $scope.content = "huifuwode";
  console.log("huifuwode");
  homeCtrlScope = angular.element('.home-page').scope();
  return homeCtrlScope.remind.replyNum = 0;
});
