// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("mifan").controller("homeCtrl", function($scope) {
  $scope.feedType = "news";
  $scope.switchFeedType = function(feedType) {
    return $scope.feedType = feedType;
  };
  $scope.$on("$viewContentLoaded", function() {
    Common.setCurrentPage("home");
    return $scope.separateHeight = $(".home-page .main").height();
  });
  $scope.askQuesConent = "";
  $scope.remind = {
    newsNum: 0,
    answerNum: 2,
    replyNum: '...'
  };
  return false;
});
