// Generated by CoffeeScript 1.7.1
Mifan.controller("homeNews", function($scope) {
  $scope.content = "zuixindongtai";
  console.log("zuixindongtai");
  return $scope.newsCollect = [
    {
      a: 1
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }
  ];
});
