// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("homeAskCtrl", function($scope) {
  $scope.askQuesConent = "";
  $scope.bgUrl = "images/beijing01.jpg";
  $scope.avatarUrl = "http://tp4.sinaimg.cn/2005321383/180/5698650002/1";
  $scope.isSending = false;
  $scope.onFocus = function() {
    return $scope.onInputing = true;
  };
  $scope.onBlur = function(force) {
    if (force || $scope.askQuesConent === "") {
      return $scope.onInputing = false;
    }
  };
  return $scope.send = function() {
    return $scope.isSending = true;
  };
});
