// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("homeCtrl", function($scope) {
  $scope.feedType = "news";
  $scope.switchFeedType = function(feedType) {
    return $scope.feedType = feedType;
  };
  $scope.$on("$viewContentLoaded", function() {
    $scope.$emit("pageChange", "home");
    return $scope.separateHeight = 0;
  });
  $scope.askQuesConent = "";
  $scope.remind = {
    newsNum: 0,
    answerNum: 2,
    replyNum: '...'
  };
  return false;
});
