// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("loginCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "login");
  });
  $scope.$watch("email + password", function() {
    return $scope.isLogValid = $scope.email && $scope.password;
  });
  $scope.isLoging = false;
  return $scope.onSubmit = function() {
    return $scope.isLoging = true;
  };
});
