// Generated by CoffeeScript 1.7.1
Mifan.controller("mDesginCtrl", function($scope, $timeout) {
  var DOC, elMDesignTextarea;
  DOC = $scope.DOC;
  elMDesignTextarea = DOC["getElementById"]("m-design-input");
  $scope.$on("setMDesignType", function(detail, msg) {
    $scope.viewType = msg;
    return $timeout(function() {
      return elMDesignTextarea.focus();
    }, 400);
  });
  $scope.$on("cancelMDesingSending", function() {
    $scope.isSending = false;
    return $scope.mDesignContent = "";
  });
  return $scope.onSubmit = function() {
    return $scope.isSending = true;
  };
});
