// Generated by CoffeeScript 1.7.1
"use strict";
angular.module("mifan").controller("meCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return Common.setCurrentPage("me");
  });
  return false;
});
