// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("msgCtrl", function($scope, $rootScope) {
  var DOC;
  DOC = $scope.DOC;
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "msg");
  });
  $scope.focus = function() {
    return console.log(111);
  };
  $scope.setMBill = function(index) {
    return $scope.toggleMBill(["love", "answer", "share"]);
  };
  return false;
});
