// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("msgCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return Common.setCurrentPage("msg");
  });
  return false;
});
