// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("msgCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "msg");
  });
  return false;
});
