// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("registerCtrl", function($scope) {
  var reg, rules, toast, validEmail, validInviteCode, validName, validPwd;
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "register");
  });
  toast = function(msg, type, time) {
    if (time == null) {
      time = 5000;
    }
    return $scope.toast(msg, type, time);
  };
  rules = {
    email: {
      reg: /^(\w)+(\.\w+)*@(\w)+((\.\w+)+)$/,
      tip: "邮箱格式错误"
    },
    pwd: {
      reg: /^[\w\~\!\@\#\$\%\^\&\*\(\)\+\`\-\=\[\]\\\{\}\|\;\'\:\"\,\.\/\<\>\?0-9a-zA-z]{6,20}$/,
      tip: "密码应该由6-40个英文字母、数字或符号组成"
    }
  };
  validEmail = function(email) {
    return rules.email.reg.test(email);
  };
  validPwd = function(pwd) {
    return pwd && rules.pwd.reg.test(pwd);
  };
  validName = function(name) {
    return !!name;
  };
  validInviteCode = function(code) {
    return !!code;
  };
  reg = {
    init: function() {
      $scope.$watch("email + password + username + invitecode", function() {
        return $scope.isRegValid = reg.valid();
      });
      $scope.isReging = false;
      $scope.onSubmit = reg.onSubmit;
      $scope.valid = reg.valid;
      return $scope.$on("onRegCb", function(event, data) {
        return reg.onSubmitCb(data);
      });
    },
    valid: function(needToast) {
      var base, email, flag, invitecode, isCodeOk, isEmailOk, isNameOk, isPwdOk, password, username;
      email = $scope.email, password = $scope.password, username = $scope.username, invitecode = $scope.invitecode;
      flag = false;
      base = !!(email && password && username && invitecode);
      isEmailOk = email && validEmail(email);
      isNameOk = username && validName(username);
      isPwdOk = password && validPwd(password);
      isCodeOk = invitecode && validInviteCode(invitecode);
      if (isEmailOk && isNameOk && isPwdOk && isCodeOk) {
        flag = true;
      } else {
        flag = false;
        if (needToast) {
          if (!isEmailOk) {
            if (email) {
              toast(rules.email.tip, "error");
            }
          }
          if (!isPwdOk) {
            if (password) {
              toast(rules.pwd.tip, "error");
            }
          }
        }
      }
      return flag;
    },
    onSubmit: function() {
      var email, invitecode, password, username;
      $scope.isReging = true;
      email = $scope.email, password = $scope.password, username = $scope.username, invitecode = $scope.invitecode;
      return $scope.$emit("onReg", {
        email: email,
        password: password,
        username: username,
        invitecode: invitecode
      });
    },
    onSubmitCb: function(data) {
      var isSuccess, msg, result, ret;
      ret = data.ret, msg = data.msg, result = data.result;
      isSuccess = false;
      $scope.isReging = false;
      if (String(ret) === "100000") {
        $scope.$emit("onRegSuccess", result);
        return toast("注册成功！", "success");
      } else {
        if (msg) {
          return toast(msg, "error");
        }
      }
    }
  };
  return reg.init();
});
