// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("registerCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "register");
  });
  $scope.$watch("email + password", function() {
    return $scope.isRegValid = $scope.email && $scope.password;
  });
  $scope.isReging = false;
  return $scope.regSubmit = function() {
    return $scope.isReging = true;
  };
});
