// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("rootCtrl", function($scope, $cookieStore, $http, $timeout, $storage, $emoji, $cacheFactory, $extend, $location, $debug) {
  var API, Ans, Ask, Cache, Comment, Follow, LoveAns, MBill, MDesign, MMenu, Notification, Page, Pagination, Toast, User, elMwrap, getUserInfo, store;
  API = $scope.API;
  $storage.put = $storage.set;
  store = IsWebapp ? $storage : $cookieStore;
  $scope.supportNum = "1万";

  /*
  用户信息，用户操作的方法
   */
  User = {
    init: function() {
      $scope.user = {};
      $scope.accessToken = $scope.UID = $scope.username = void 0;
      $scope.isLogin = false;
      $scope.$on("onLogined", User.onLoginCb);
      $scope.User = User;
      return User.getLocal();
    },
    set: function(user) {
      return $extend($scope.user, user);
    },
    getRemote: function() {
      var uid, url;
      uid = $scope.user.uid;
      url = ["" + API.userInfo, (IsDebug ? "" : "/" + uid), "" + $scope.privacyParam, "&uid=" + uid].join("");
      return $http.get(url).success(User.getRemoteCb).error(User.getRemoteErrorCb);
    },
    getRemoteCb: function(data) {
      var ret, user;
      ret = data["ret"];
      if (String(ret) === "100000") {
        user = data["result"];
        User.set(user);
        $scope.isLogin = true;
        return $scope.$broadcast("getHomeNews");
      } else {
        return User.onOutOfDate();
      }
    },
    getRemoteErrorCb: function(data) {},
    isLocalLogin: false,
    getLocal: function() {
      var accessToken, uid;
      uid = store.get("mUID");
      accessToken = store.get("mAccessToken");
      if (uid && accessToken) {
        return User.getLocalCb(uid, accessToken);
      } else {
        return User.login();
      }
    },
    getLocalCb: function(uid, accessToken) {
      var username;
      User.isLocalLogin = true;
      username = store.get("mUsername");
      $scope.user.uid = $scope.UID = uid;
      $scope.user.face_60 = $scope.user.face_120 = $scope.DEFAULT_FACE;
      $scope.user.username = $scope.username = username;
      $scope.accessToken = accessToken;
      User.setPrivacy();
      return User.getRemote();
    },
    setPrivacy: function() {
      var accessToken, uid;
      accessToken = $scope.accessToken;
      uid = $scope.UID;
      $scope.privacyParam = "?access_token=" + accessToken + "&userid=" + uid;
      return $scope.privacyParamDir = "/access_token/" + accessToken + "/userid/" + uid;
    },
    store: function(user) {
      store.put("mUID", user["userid"]);
      store.put("mUsername", user["username"]);
      return store.put("mAccessToken", $scope.accessToken);
    },
    remove: function() {
      store.remove("mUID");
      store.remove("mUsername");
      return store.remove("mAccessToken");
    },
    onLoginCb: function(event, result) {
      var accessToken, user;
      $scope.isLogin = true;
      accessToken = $scope.accessToken = result["accesstoken"];
      user = result["user"];
      $scope.username = user["username"];
      $scope.UID = user["userid"];
      $scope.user.accessToken = accessToken;
      User.set(user);
      User.store(user);
      User.setPrivacy();
      return $location.path("/");
    },
    onOutOfDate: function() {
      User.remove();
      $scope.isLogin = false;
      return User.login();
    },
    logout: function() {
      $scope.user = {};
      $cookieStore.remove("mUID");
      $cookieStore.remove("mAccessToken");
      $scope.isLogin = false;
      return $timeout(User.login, 200);
    },
    login: function() {
      if (!$location.path().match(/login/)) {
        return $location.path("login");
      }
    }
  };
  User.init();

  /*
  页面切换，页面操作
   */
  elMwrap = DOC["getElementById"]("m-wrap");
  Page = {
    init: function() {
      $scope.page = "home";
      $scope.scrollBody1Px = Page.scrollBody1Px;
      $scope.backToTop = Page.onBackToTop;
      $scope.$on("pageChange", Page.onPageChangeCb);
      $scope.logout = User.logout;
      $scope.Page = Page;
      return $scope.$on("onScrollTop", function(e, msg) {
        return Page.onBackToTop();
      });
    },
    onPageChangeCb: function(event, msg) {
      $scope.page = msg;
      elMwrap["scrollTop"] = 1;
      return Pagination.clear();
    },
    onBackToTop: function(isM) {
      return (isM ? elMwrap : BODY)["scrollTop"] = 0;
    },
    scrollBody1Px: function() {
      if (elMwrap["scrollTop"] === 0) {
        return elMwrap["scrollTop"] = 1;
      }
    }
  };
  Page.init();

  /*
  移动用户侧边栏菜单
   */
  MMenu = {
    init: function() {
      $scope.isMMenuOpen = false;
      $scope.toggleMMenu = MMenu.toggle;
      return $scope.MMenu = MMenu;
    },
    toggle: function() {
      return $scope.isMMenuOpen = !$scope.isMMenuOpen;
    }
  };
  MMenu.init();

  /*
  移动全屏输入框
   */
  MDesign = {
    init: function() {
      $scope.isMDesignOpen = false;
      $scope.isMDesignOpenMask = false;
      $scope.toggleMDesign = MDesign.toggle;
      return $scope.$on("onMDesignSend", MDesign.onSend);
    },
    toggle: function(type) {
      if ($scope.isMDesignOpen) {
        $scope.isMDesignOpenMask = !$scope.isMDesignOpenMask;
        $timeout(function() {
          return $scope.isMDesignOpen = !$scope.isMDesignOpen;
        }, 200);
      } else {
        $scope.isMDesignOpen = !$scope.isMDesignOpen;
        $timeout(function() {
          return $scope.isMDesignOpenMask = !$scope.isMDesignOpenMask;
        }, 200);
      }
      if ($scope.isMBillOpen) {
        MBill.toggle();
      }
      if (type && $scope.isMDesignOpen) {
        $scope.$broadcast("setMDesignType", type);
      }
      if (!$scope.isMDesignOpen) {
        return $scope.$broadcast("cancelMDesingSending");
      }
    },
    onSend: function(event, msg) {
      var content, type;
      type = msg.type;
      content = msg.content;
      switch (type) {
        case "ask":
          return Ask.ask(content);
      }
    },
    onOpen: function() {},
    onClose: function() {}
  };
  MDesign.init();

  /*
  移动底部弹出交互菜单
   */
  MBill = {
    init: function() {
      $scope.isMBillOpen = false;
      $scope.isMBillOpenMask = false;
      return $scope.toggleMBill = MBill.toggle;
    },
    toggle: function(billList) {
      if ($scope.isMBillOpen) {
        $scope.isMBillOpenMask = !$scope.isMBillOpenMask;
        return $timeout(function() {
          return $scope.isMBillOpen = !$scope.isMBillOpen;
        }, 200);
      } else {
        $scope.$broadcast("setBillList", billList);
        $scope.isMBillOpen = !$scope.isMBillOpen;
        return $timeout(function() {
          return $scope.isMBillOpenMask = !$scope.isMBillOpenMask;
        }, 100);
      }
    }
  };
  MBill.init();

  /*
  提问
   */
  Ask = {
    init: function() {
      return $scope.askQues = Ask.ask;
    },
    ask: function(data) {
      var query, url;
      url = "" + API.ask + $scope.privacyParamDir;
      if (IsDebug) {
        url = API.ask;
      }
      query = {
        content: data.content
      };
      if (data.foruser) {
        query.foruser = data.foruser;
      }
      return (IsDebug ? $http.get : $http.post)(url, query).success(Ask.askCb);
    },
    askCb: function(data) {
      var ret;
      ret = data["ret"];
      if (String(ret) === "100000") {
        $scope.$broadcast("onAskQuesSuccess", {
          queId: data["result"]
        });
        return $scope.$broadcast("onMDesignSendSuccess");
      } else {
        return $scope.$broadcast("onAskQuesFail", {
          msg: data.msg
        });
      }
    }
  };
  Ask.init();

  /*
  缓存的配置
   */
  Cache = {
    init: function() {
      var $httpDefaultCache, lruCache;
      $httpDefaultCache = $cacheFactory.get($http);
      return lruCache = $cacheFactory("lruCache", {
        capacity: 8
      });
    }
  };
  Cache.init();
  Notification = {
    init: function() {
      return Notification.get();
    },
    time: 0,
    get: function() {
      var api;
      api = IsDebug ? API.notice : "" + API.notice + $scope.privacyParamDir;
      $http.get(api).success(Notification.cb);
      return Notification.time++;
    },
    cb: function(data) {
      if (data.msg === "ok") {
        $scope.msgCount = data.result || 0;
      }
      return $timeout(Notification.get, 30000);
    }
  };
  Notification.init();
  Toast = {
    init: function() {
      $scope.toast = Toast.toast;
      return $scope.Toast = Toast;
    },
    text: "",
    isShow: false,
    type: "primary",
    toast: function(msg, type) {
      Toast.text = msg;
      Toast.isShow = true;
      Toast.type = type || "success";
      return $timeout((function() {
        return Toast.isShow = false;
      }), 3000);
    }
  };
  Toast.init();
  Follow = {
    init: function() {
      $scope.$on("follow", function(event, data) {
        return Follow.follow(data.userid);
      });
      return $scope.$on("unfollow", function(event, data) {
        return Follow.unfollow(data.userid);
      });
    },
    send: function(api, cb) {
      return (IsDebug ? $http.get : $http.post)(api).success(cb);
    },
    follow: function(uid) {
      var api;
      api = "" + API.follow + $scope.privacyParamDir + "/userid_follow/" + uid;
      if (IsDebug) {
        api = API.follow;
      }
      return Follow.send(api, Follow.followCb);
    },
    followCb: function(data) {
      return $scope.$broadcast("followCb", data);
    },
    unfollow: function(uid) {
      var api;
      api = "" + API.unfollow + $scope.privacyParamDir + "/userid_follow/" + uid;
      if (IsDebug) {
        api = API.unfollow;
      }
      return Follow.send(api, Follow.unfollowCb);
    },
    unfollowCb: function(data) {
      return $scope.$broadcast("unfollowCb", data);
    }
  };
  Follow.init();
  LoveAns = {
    init: function() {
      $scope.loveAns = LoveAns.send;
      return $scope.$on("loveans", function(event, data) {
        return LoveAns.send(data);
      });
    },
    feed: null,
    send: function(data) {
      var api, query;
      api = "" + API.loveanswer + $scope.privacyParamDir;
      if (IsDebug) {
        api = API.loveanswer;
      }
      query = data;
      return (IsDebug ? $http.get : $http.post)(api, query).success(LoveAns.sendCb);
    },
    sendCb: function(data) {
      return $scope.$broadcast("loveansCb", data);
    }
  };
  LoveAns.init();
  Ans = {
    init: function() {
      $scope.Ans = Ans.send;
      return $scope.$on("ans", function(event, data) {
        return Ans.send(data);
      });
    },
    send: function(data) {
      var api, query;
      api = "" + API.answer + $scope.privacyParamDir;
      if (IsDebug) {
        api = API.answer;
      }
      query = {
        askid: data.askid,
        content: data.content
      };
      return (IsDebug ? $http.get : $http.post)(api, query).success(function(data) {
        return Ans.sendCb(data);
      });
    },
    sendCb: function(data) {
      return $scope.$broadcast("ansCb", data);
    }
  };
  Ans.init();
  getUserInfo = {
    init: function() {
      return $scope.$on("getUserInfo", function(e, data) {
        return getUserInfo.get(data);
      });
    },
    get: function(data) {
      var api, uid;
      uid = data.uid;
      api = ["" + API.userInfo, (IsDebug ? "" : "/" + uid), "" + $scope.privacyParam, "&uid=" + uid].join("");
      return $http.get(api).success(getUserInfo.getCb);
    },
    getCb: function(data) {
      var msg, result;
      msg = data.msg, result = data.result;
      return $scope.$broadcast("getUserInfoCb", data);
    }
  };
  getUserInfo.init();
  Comment = {
    init: function() {
      $scope.$on("comment", function(e, data) {
        return Comment.send(data);
      });
      return $scope.$on("getcomment", function(e, data) {
        return Comment.get(data);
      });
    },
    send: function(data) {
      var api;
      api = "" + API.comment + $scope.privacyParamDir;
      if (IsDebug) {
        api = API.comment;
      }
      return (IsDebug ? $http.get : $http.post)(api, data).success(function(data) {
        return Comment.sendCb(data);
      });
    },
    sendCb: function(data) {
      return $scope.$broadcast("commentCb", data);
    },
    get: function(data) {
      var api;
      api = "" + API.getComment + $scope.privacyParamDir + "/answerid/" + data.answerid;
      if (IsDebug) {
        api = API.getComment;
      }
      return $http.get(api).success(function(data) {
        return Comment.getCb(data);
      });
    },
    getCb: function(data) {
      return $scope.$broadcast("getcommentCb", data);
    }
  };
  Comment.init();
  Pagination = {
    init: function() {
      $scope.page = {};
      $scope.isPageLoading = false;
      $scope.$on("onPaginationStartChange", Pagination.onChange);
      $scope.$on("onPaginationGeted", Pagination.set);
      return $scope.$on("onClearPaginationData", Pagination.clear);
    },
    onChange: function(event, msg) {
      $scope.curPage = msg;
      return $scope.isPageLoading = true;
    },
    curPage: 1,
    totalPage: 0,
    set: function(e, pageData) {
      var curPage, totalPage, _i, _results;
      curPage = Number(pageData['cur_page']);
      totalPage = Number(pageData['total_page']);
      Pagination.curPage = curPage;
      Pagination.totalPage = totalPage;
      $scope.isPageLoading = false;
      $scope.curPage = curPage;
      $scope.totalPage = totalPage;
      $scope.pages = (function() {
        _results = [];
        for (var _i = 1; 1 <= totalPage ? _i <= totalPage : _i >= totalPage; 1 <= totalPage ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this);
      return Page.onBackToTop();
    },
    clear: function() {
      $scope.isPageLoading = false;
      $scope.curPage = 1;
      $scope.totalPage = 0;
      return $scope.pages = [];
    }
  };
  return Pagination.init();
});
