// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("welcomeCtrl", [
  "$scope", "$location", function($scope, $location) {
    $scope.$on("$viewContentLoaded", function() {
      return Common.setCurrentPage("welcome");
    });
    $location.$$rewrite("/home");
    console.log($location);
    return false;
  }
]);
