// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("welcomeCtrl", [
  "$scope", "$location", function($scope, $location) {
    $scope.$on("$viewContentLoaded", function() {
      return Common.setCurrentPage("welcome");
    });
    $scope.$watch("email + password", function() {
      return $scope.isLoginValid = $scope.email && $scope.password;
    });
    $scope.loginSubmit = function() {};
    return false;
  }
]);
