// Generated by CoffeeScript 1.7.1
Mifan.controller("addLoveCtrl", function($scope, $http) {
  var loveAns;
  loveAns = {
    init: function() {
      $scope.loveAns = loveAns.send;
      return $scope.$on("loveansCb", function(event, data) {
        return loveAns.sendCb(data);
      });
    },
    feed: null,
    send: function(item, point) {
      var data;
      if (item.love.iflove) {
        return false;
      }
      data = {
        answerid: item.answer.answerid
      };
      loveAns.feed = item;
      return $scope.$emit("loveans", data);
    },
    sendCb: function(data) {
      var msg, result, ret, toastType;
      ret = data.ret, msg = data.msg, result = data.result;
      toastType = "";
      if (String(ret) === "100000") {
        if (loveAns.feed) {
          loveAns.feed.love.iflove = 1;
          loveAns.feed.answer.digg = result;
        }
        msg = "喜欢成功";
      } else {
        toastType = "warn";
      }
      return $scope.toast(msg, toastType);
    }
  };
  return loveAns.init();
});
