// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("homeAskCtrl", function($scope, $timeout) {
  $scope.quesContent = "";
  $scope.isSending = false;
  $scope.send = function() {
    $scope.isSending = true;
    return $scope.askQues($scope.quesContent);
  };
  return $scope.$on("onAskQuesSuccess", function(event, msg) {
    $scope.quesContent = "";
    $scope.isSending = false;
    $scope.isSendSucs = true;
    return $timeout(function() {
      return $scope.isSendSucs = false;
    }, 1000);
  });
});
