// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("homeAskCtrl", function($scope, $timeout) {
  var clearAsk;
  $scope.quesContent = "";
  $scope.isSending = false;
  $scope.send = function() {
    $scope.isSending = true;
    return $scope.askQues({
      content: $scope.quesContent
    });
  };
  clearAsk = function() {
    $scope.isSending = false;
    return $timeout(function() {
      return $scope.isSendSucs = false;
    }, 1000);
  };
  $scope.$on("onAskQuesSuccess", function(event, msg) {
    $scope.quesContent = "";
    $scope.isSendSucs = true;
    $scope.toast("提问成功！");
    return clearAsk();
  });
  return $scope.$on("onAskQuesFail", function(event, msg) {
    $scope.toast(msg.msg);
    return clearAsk();
  });
});
