// Generated by CoffeeScript 1.7.1
Mifan.controller("homeFeed", function($scope, $http) {
  var comment, feed, loveAns;
  feed = {
    init: function() {}
  };
  feed.init();
  $scope.toggleMBubble = function(index) {
    return $scope.newsCollect[index].bblActv = !$scope.newsCollect[index].bblActv;
  };
  $scope.setMBill = function(index) {
    return $scope.toggleMBill(["love", "comment", "share"]);
  };
  loveAns = {
    init: function() {
      $scope.loveAns = loveAns.send;
      return $scope.$on("loveansCb", function(event, data) {
        return loveAns.sendCb(data);
      });
    },
    feed: null,
    send: function(item, point) {
      var data;
      if (item.love.iflove) {
        return false;
      }
      data = {
        answerid: item.answer.answerid
      };
      loveAns.feed = item;
      return $scope.$emit("loveans", data);
    },
    sendCb: function(data) {
      var msg, result, ret, toastType;
      ret = data.ret, msg = data.msg, result = data.result;
      toastType = "";
      if (String(ret) === "100000") {
        loveAns.feed.love.iflove = 1;
        loveAns.feed.answer.digg = result;
        msg = "喜欢成功";
      } else {
        toastType = "warn";
      }
      return $scope.toast(msg, toastType);
    }
  };
  loveAns.init();
  comment = {
    init: function() {
      $scope.comment = comment.send;
      $scope.$on("commentCb", function(e, data) {
        return comment.sendCb(data);
      });
      $scope.$on("getcommentCb", function(e, data) {
        return comment.getCb(data);
      });
      $scope.expandCmtFn = comment.expand;
      $scope.expandReplyFn = comment.replyExpand;
      return $scope.reply = comment.reply;
    },
    point: null,
    feed: null,
    getcommentFeed: null,
    content: "",
    send: function(news, point, isReply) {
      var content;
      point.isSendingCmt = true;
      content = isReply ? "回复@" + comment.replyUsername + ": " + point.rplContent : point.cmtContent;
      comment.content = content;
      $scope.$emit("comment", {
        askid: news.ask.askid,
        answerid: news.answer.answerid,
        content: content
      });
      comment.point = point;
      return comment.feed = news;
    },
    sendCb: function(data) {
      var cmt, msg, result, ret, toastType, user;
      ret = data.ret, msg = data.msg, result = data.result;
      toastType = "";
      if (String(ret) === "100000") {

      } else {
        toastType = "warn";
      }
      $scope.toast(msg);
      comment.point.isSendingCmt = false;
      comment.point.isSendingRpl = false;
      comment.point.cmtContent = "";
      comment.point.rplContent = "";
      comment.point.expandReply = false;
      user = $scope.user;
      cmt = {
        content: comment.content,
        addtime: +(new Date),
        user: {
          "userid": user.userid,
          "username": user.username,
          "email": user.email,
          "face": user.email,
          "path": user.path,
          "face_120": user.face_120,
          "face_60": user.face_60
        }
      };
      return comment.feed.comment.splice(0, 0, cmt);
    },
    expand: function(feed, point) {
      point.expandCmt = !point.expandCmt;
      if (point.expandCmt) {
        comment.get(feed, point);
        return comment.getcommentFeed = feed;
      }
    },
    get: function(feed, point) {
      var data;
      data = {
        answerid: feed.answer.answerid
      };
      return $scope.$emit("getcomment", data);
    },
    getCb: function(data) {
      var msg, result, ret;
      ret = data.ret, msg = data.msg, result = data.result;
      return comment.getcommentFeed.comment = result;
    },
    replyExpand: function(feed, point) {
      return point.expandReply = !point.expandReply;
    },
    replyUsername: "",
    reply: function(index, feed, point) {
      var cmt, username;
      cmt = feed.comment[index];
      username = cmt.user.username;
      comment.replyUsername = username;
      point.isSendingRpl = true;
      return comment.send(feed, point, true);
    },
    replyCb: function(data) {}
  };
  return comment.init();
});
