// Generated by CoffeeScript 1.7.1
Mifan.controller("homeFeed", function($scope, $http) {
  var feed;
  feed = {
    init: function() {}
  };
  feed.init();
  $scope.toggleMBubble = function(index) {
    return $scope.newsCollect[index].bblActv = !$scope.newsCollect[index].bblActv;
  };
  return $scope.setMBill = function(index) {
    return $scope.toggleMBill(["love", "comment", "share"]);
  };
});
