// Generated by CoffeeScript 1.7.1
Mifan.controller("homeNews", function($scope, $timeout, $http, $time) {
  var API, news;
  API = $scope.API;
  $scope.content = "";
  $scope.newsCollect = [];
  news = {
    init: function() {
      $scope.$on("getHomeNews", function() {
        return news.get();
      });
      if ($scope.isLogin) {
        return news.get();
      }
    },
    get: function() {
      var cb, url;
      url = "" + API.news + $scope.privacyParamDir;
      if (IsDebug) {
        url = API.news;
      }
      cb = function(data) {
        var ret;
        ret = data['ret'];
        if (String(ret) === "100000") {
          return $scope.newsCollect = data['result'];
        }
      };
      return $http.get(url, {
        cache: "lruCache"
      }).success(cb);
    }
  };
  return news.init();
});
