// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("meCtrl", function($scope, $timeout, $http) {
  var legalFeedTypes, me;
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "me");
  });
  legalFeedTypes = ["ask", "answer", "love"];
  $scope.feedType = "ask";
  $scope.ta = "我";
  $scope.loadingMore = function() {
    return $scope.isLoading = true;
  };
  $scope.switchFeed = function(type) {
    type = type || "ask";
    $scope.feedType = type;
    return $scope.isLoading = false;
  };
  $scope.profile = $scope.user;
  me = {
    init: function() {
      me.getMyAsk();
      $timeout(me.getMyAnswer, 300);
      $timeout(me.getMyLove, 600);
      $scope.myAskMsg = $scope.myAnswerMsg = $scope.myLoveMsg = "";
      $scope.myAsk = $scope.myAnswer = $scope.myLove = [];
      $scope.myAskMore = $scope.myAnswerMore = $scope.myLoveMore = false;
      return $scope.myself = true;
    },
    feedWatcher: function(feed) {
      if (feed == null) {
        feed = "ask";
      }
    },
    getMyAsk: function() {
      var api;
      api = "" + API.myask + $scope.privacyParamDir;
      if (IsDebug) {
        api = API.myask;
      }
      return $http.get(api).success(me.getMyAskCb);
    },
    getMyAskCb: function(data) {
      if (String(data.msg) === "ok") {
        return $scope.myAsk = data.result || [];
      } else {
        return $scope.myAskMsg = data.msg;
      }
    },
    getMyAnswer: function() {
      var api;
      api = "" + API.myanswer + $scope.privacyParamDir;
      if (IsDebug) {
        api = API.myanswer;
      }
      return $http.get(api).success(me.getMyAnswerCb);
    },
    getMyAnswerCb: function(data) {
      if (String(data.msg) === "ok") {
        return $scope.myAnswer = data.result || [];
      } else {
        return $scope.myAnswerMsg = data.msg;
      }
    },
    getMyLove: function() {}
  };
  return me.init();
});
