// Generated by CoffeeScript 1.7.1
var BODY, DOC, IsAndroid, IsAndroidPad, IsBlackBerry, IsChrome, IsDebug, IsIE, IsIEMobile, IsIOS, IsIPad, IsIPhone, IsPhone, IsTouch, IsWebapp, IsWeixin, IsWindowsPhone, LOC, NA, NG, UA, WIN;

DOC = document;

WIN = window;

LOC = location;

BODY = DOC['body'];


/*
设备是否支持触摸事件
这里使用WIN.hasOwnProperty('ontouchend')在Android上会得到错误的结果
@type {boolean}
 */

IsTouch = "ontouchend" in WIN;

NA = WIN.navigator;

UA = NA.userAgent;

IsAndroid = /Android|HTC/i.test(UA) || /Linux/i.test(NA.platform + "");

IsAndroidPad = IsAndroid && /Pad/i.test(UA);

IsIPad = !IsAndroid && /iPad/i.test(UA);

IsIPhone = !IsAndroid && /iPod|iPhone/i.test(UA);

IsIOS = IsIPad || IsIPhone;

IsWindowsPhone = /Windows Phone/i.test(UA);

IsBlackBerry = /BB10|BlackBerry/i.test(UA);

IsIEMobile = /IEMobile/i.test(UA);

IsIE = !!DOC.all;

IsWeixin = /MicroMessenger/i.test(UA);

IsChrome = !!WIN['chrome'];

IsPhone = IsIPhone || (IsAndroid && !IsAndroidPad);

IsWebapp = !!NA["standalone"];

NG = WIN['angular'];

IsDebug = LOC["port"] === "9000";
