// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("msgCtrl", function($scope, $rootScope, $http, $debug, $timeout) {
  var DOC, ans, message;
  DOC = $scope.DOC;
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "msg");
  });
  $scope.setMBill = function(index) {
    return $scope.toggleMBill(["love", "answer", "share"]);
  };
  message = {
    init: function() {
      message.getAskMe();
      $scope.askMe = [];
      $scope.askMeMsg = "";
      $scope.askMeMore = false;
      return $scope.getPage = message.getAskMe;
    },
    getAskMe: function(page) {
      var api;
      if (page == null) {
        page = 1;
      }
      if ($scope.isPageLoading) {
        return false;
      }
      api = "" + API.askme + $scope.privacyParamDir + "/type/askme/page/" + page;
      if (IsDebug) {
        api = API.askme;
      }
      $http.get(api).success(message.getAskMeCb);
      return $scope.$emit("onPaginationStartChange", page);
    },
    getAskMeCb: function(data) {
      var list, msg, result, ret;
      ret = data.ret, msg = data.msg, result = data.result;
      if (msg === "ok") {
        list = result != null ? result['list'] : void 0;
        $scope.askMe = list || [];
        message.count = list.length;
        $scope.$emit("onPaginationGeted", result['page']);
      } else {
        $scope.errorMsg = msg;
      }
      return $scope.dataLoaded = true;
    },
    count: 0
  };
  message.init();
  ans = {
    init: function() {
      $scope.sendAns = ans.send;
      $scope.$watch($scope.askMe, function() {
        if ($scope.askMe.length === 0) {
          return $scope.askMeMsg = "空";
        }
      });
      return $scope.$on("ansCb", function(event, data) {
        return ans.sendCb(data);
      });
    },
    item: null,
    send: function(item, data) {
      var query;
      item.isSending = true;
      ans.item = item;
      query = {
        askid: data.askid,
        content: item.content
      };
      return $scope.$emit("ans", query);
    },
    sendCb: function(data) {
      var item, toastType;
      item = ans.item;
      item.content = "";
      item.isSending = false;
      toastType = "";
      if (String(data.ret) === "100000") {
        $timeout(((function(_this) {
          return function() {
            item.isSendSucs = true;
            item.answerd = true;
            item.isSendSucs = false;
            ans.count++;
            if (ans.count >= message.count) {
              return $scope.askMe.length = 0;
            }
          };
        })(this)), 100);
      } else {
        toastType = "warn";
      }
      return $scope.toast(data.msg, toastType);
    },
    count: 0
  };
  ans.init();
  return false;
});
