// Generated by CoffeeScript 1.7.1
Mifan.controller("userAskCtrl", function($scope, $timeout, $http, $debug, $routeParams) {
  var userid;
  $scope.quesContent = "";
  userid = $routeParams.id;
  $scope.send = function() {
    $scope.isSending = true;
    return $scope.askQues({
      content: $scope.quesContent,
      foruser: userid
    });
  };
  $scope.$on("onAskQuesSuccess", function(event, msg) {
    $scope.quesContent = "";
    $scope.isSending = false;
    $scope.isSendSucs = true;
    $timeout(function() {
      return $scope.isSendSucs = $scope.showAskBox = false;
    }, 1000);
    return $scope.toast("提问成功！");
  });
  return $scope.$on("onAskQuesFail", function(event, msg) {
    $scope.toast(msg.msg);
    $scope.isSending = false;
    return $timeout(function() {
      return $scope.isSendSucs = false;
    }, 1000);
  });
});
