// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("userCtrl", function($scope, $timeout, $http, $routeParams) {
  var legalFeedTypes, user, userid;
  userid = $routeParams.id;
  if ($scope.UID === userid) {
    return LOC["href"] = "#!/me";
  }
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "user");
  });
  legalFeedTypes = ["ask", "answer", "love"];
  $scope.feedType = "ask";
  $scope.loadingMore = function() {
    return $scope.isLoading = true;
  };
  $scope.switchFeed = function(type) {
    type = type || "ask";
    $scope.feedType = type;
    return $scope.isLoading = false;
  };
  user = {
    init: function() {
      user.getMyAsk();
      $timeout(user.getMyAnswer, 500);
      $scope.myAskMsg = $scope.myAnswerMsg = $scope.myLoveMsg = "";
      $scope.myAsk = $scope.myAnswer = $scope.myLove = [];
      $scope.myAskMore = $scope.myAnswerMore = $scope.myLoveMore = false;
      return $scope.followed = false;
    },
    getMyAsk: function() {
      var api;
      api = "" + API.myask + $scope.privacyParamDir;
      if (IsDebug) {
        api = API.myask;
      }
      return $http.get(api).success(user.getMyAskCb);
    },
    getMyAskCb: function(data) {
      if (String(data.msg) === "ok") {
        return $scope.myAsk = data.result || [];
      } else {
        return $scope.myAskMsg = data.msg;
      }
    },
    getMyAnswer: function() {
      var api;
      api = "" + API.myanswer + $scope.privacyParamDir;
      if (IsDebug) {
        api = API.myanswer;
      }
      return $http.get(api).success(user.getMyAnswerCb);
    },
    getMyAnswerCb: function(data) {
      if (String(data.msg) === "ok") {
        return $scope.myAnswer = data.result || [];
      } else {
        return $scope.myAnswerMsg = data.msg;
      }
    }
  };
  user.init();
  return $scope.askHim = function() {
    return $scope.showAskBox = true;
  };
});
