// Generated by CoffeeScript 1.7.1
Mifan.controller("mDesginCtrl", function($scope, $timeout) {
  var DOC, elMDesignTextarea, titleMap;
  DOC = $scope.DOC;
  elMDesignTextarea = DOC["getElementById"]("m-design-input");
  titleMap = {
    'ask': "提出问题",
    'comment': "评论"
  };
  $scope.$on("setMDesignType", function(detail, msg) {
    $scope.viewType = msg;
    $scope.title = titleMap[msg];
    return $timeout(function() {
      return elMDesignTextarea.focus();
    }, 800);
  });
  $scope.$on("cancelMDesingSending", function() {
    $scope.isSending = false;
    return $scope.mDesignContent = "";
  });
  return $scope.onSubmit = function() {
    return $scope.isSending = true;
  };
});
