// Generated by CoffeeScript 1.7.1
Mifan.controller("mDesginCtrl", function($scope, $timeout) {
  var DOC, elMDesignTextarea, sendData, titleMap;
  DOC = $scope.DOC;
  elMDesignTextarea = DOC["getElementById"]("m-design-input");
  titleMap = {
    "ask": "提出问题",
    "comment": "评论",
    "answer": "回答"
  };
  $scope.mDesignContent = "";
  sendData = {};
  $scope.$on("setMDesignType", function(evet, msg) {
    $scope.viewType = msg;
    $scope.title = titleMap[msg];
    switch (msg) {
      case "ask":
        sendData = {
          type: msg,
          content: $scope.mDesignContent
        };
    }
    return $timeout(function() {
      return elMDesignTextarea.focus();
    }, 800);
  });
  $scope.$on("cancelMDesingSending", function() {
    $scope.isSending = false;
    return $scope.mDesignContent = "";
  });
  $scope.onSubmit = function() {
    $scope.isSending = true;
    return $scope.$emit("onMDesignSend", sendData);
  };
  return $scope.$on("onMDesignSendSuccess", function(event, msg) {
    $scope.mDesignContent = "";
    $scope.isSending = false;
    $scope.isSendSucs = true;
    return $timeout(function() {
      $scope.isSendSucs = false;
      if ($scope.isMDesignOpen) {
        return $scope.toggleMDesign();
      }
    }, 800);
  });
});
