// Generated by CoffeeScript 1.7.1
(function(window, angular) {
  var extend;
  extend = function(src, dist) {
    var name;
    for (name in dist) {
      src[name] = dist[name];
    }
    return src;
  };
  return (angular.module("binnng.extend", [])).factory("$extend", function() {
    return extend;
  });
})(window, angular);
