// Generated by CoffeeScript 1.7.1
(function(window, angular) {
  var M, random;
  M = Math;
  random = M.random;
  random["in"] = function(array) {
    var len, max, min;
    len = array.length;
    min = array[0];
    max = array[len - 1];
    return M.floor(min + random() * (max - min));
  };
  return (angular.module("binnng/random", [])).factory("$random", function() {
    return random;
  });
})(window, angular);
