// Generated by CoffeeScript 1.7.1
"use strict";
var Common;

Common = {
  setCurrentPage: function(currentPage) {
    var headScope;
    headScope = angular.element(".header").scope();
    return headScope.currentPage = currentPage;
  }
};
