// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("404Ctrl", function($scope) {
  $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "404");
  });
  return false;
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("homeCtrl", function($scope) {
  $scope.feedType = "news";
  $scope.switchFeedType = function(feedType) {
    return $scope.feedType = feedType;
  };
  $scope.$on("$viewContentLoaded", function() {
    $scope.$emit("pageChange", "home");
    return $scope.separateHeight = 0;
  });
  $scope.askQuesConent = "";
  $scope.remind = {
    newsNum: 0,
    answerNum: 2,
    replyNum: '...'
  };
  return false;
});

// Generated by CoffeeScript 1.7.1
Mifan.controller("homeAnswer", function($scope) {
  var homeCtrlScope;
  $scope.content = "huidawode";
  console.log("huidawode");
  homeCtrlScope = angular.element('.home-page').scope();
  return homeCtrlScope.remind.answerNum = 0;
});

// Generated by CoffeeScript 1.7.1
Mifan.controller("homeNews", function($scope) {
  $scope.content = "zuixindongtai";
  console.log("zuixindongtai");
  return $scope.newsCollect = [
    {
      a: 1
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }
  ];
});

// Generated by CoffeeScript 1.7.1
Mifan.controller("homeReply", function($scope) {
  var homeCtrlScope;
  $scope.content = "huifuwode";
  console.log("huifuwode");
  homeCtrlScope = angular.element('.home-page').scope();
  return homeCtrlScope.remind.replyNum = 0;
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("meCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "me");
  });
  return false;
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("msgCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "msg");
  });
  return false;
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("rootCtrl", function($scope) {
  $scope.currentPage = "home";
  $scope.username = "";
  $scope.supportNum = "1万";
  $scope.dropdownOpen = false;
  $scope.toggleDropdown = function() {
    return $scope.dropdownOpen = !$scope.dropdownOpen;
  };
  $scope.support = function() {
    return alert(1);
  };
  $scope.$on("pageChange", function(e, msg) {
    return $scope.currentPage = msg;
  });
  return false;
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("welcomeCtrl", [
  "$scope", function($scope) {
    $scope.$on("$viewContentLoaded", function() {
      return $scope.$emit("pageChange", "welcome");
    });
    $scope.$watch("email + password", function() {
      return $scope.isLoginValid = $scope.email && $scope.password;
    });
    $scope.isLoginBox = false;
    $scope.isLoging = false;
    $scope.isReging = false;
    $scope.toggleLogin = function() {
      return $scope.isLoginBox = !$scope.isLoginBox;
    };
    $scope.loginSubmit = function() {
      return $scope.isLoging = true;
    };
    $scope.regSubmit = function() {
      return $scope.isReging = true;
    };
    return false;
  }
]);
