// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("404Ctrl", function($scope) {
  $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "404");
  });
  return false;
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("globalCtrl", function($scope) {
  var BASE_API_PATH, BODY, DOC, IsAndroid, IsBlackBerry, IsChrome, IsDebug, IsIE, IsIEMobile, IsIOS, IsIPad, IsIPhone, IsTouch, IsWeixin, IsWindowsPhone, LOC, NA, NG, UA, WIN;
  DOC = document;
  WIN = window;
  LOC = location;
  BODY = DOC['body'];

  /*
  设备是否支持触摸事件
  这里使用WIN.hasOwnProperty('ontouchend')在Android上会得到错误的结果
  @type {boolean}
   */
  IsTouch = "ontouchend" in WIN;
  NA = WIN.navigator;
  UA = NA.userAgent;
  IsAndroid = /Android|HTC/i.test(UA) || /Linux/i.test(NA.platform + "");
  IsIPad = !IsAndroid && /iPad/i.test(UA);
  IsIPhone = !IsAndroid && /iPod|iPhone/i.test(UA);
  IsIOS = IsIPad || IsIPhone;
  IsWindowsPhone = /Windows Phone/i.test(UA);
  IsBlackBerry = /BB10|BlackBerry/i.test(UA);
  IsIEMobile = /IEMobile/i.test(UA);
  IsIE = !!DOC.all;
  IsWeixin = /MicroMessenger/i.test(UA);
  IsChrome = !!WIN['chrome'];
  NG = WIN['angular'];
  $scope.WIN = WIN;
  $scope.DOC = DOC;
  $scope.LOC = LOC;
  $scope.BODY = BODY;
  $scope.IsIPhone = IsIPhone;
  $scope.IsIPad = IsIPad;
  $scope.IsIOS = IsIOS;
  $scope.IsAndroid = IsAndroid;
  $scope.IsIEMobile = IsIEMobile;
  $scope.IsWeixin = IsWeixin;
  $scope.IsTouch = $scope.IsMobile = IsTouch;
  $scope.IsChrome = IsChrome;
  $scope.IsIE = IsIE;
  IsDebug = LOC["port"] === "9000";
  $scope.IsDebug = IsDebug;
  BASE_API_PATH = "/mifan/service/index.php";
  $scope.API = {
    user: "" + BASE_API_PATH + "/user/usersession/user",
    userInfo: "" + BASE_API_PATH + "/user/userinfo/user/id"
  };
  if (IsDebug) {
    BASE_API_PATH = "/data";
    $scope.API = {
      user: "" + BASE_API_PATH + "/user.json",
      userInfo: "" + BASE_API_PATH + "/user-info.json"
    };
  }
  return $scope.DEFAULT_FACE = "http://mifan.us/public/images/user_normal.jpg";
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("headCtrl", function($scope) {
  $scope.dropdownOpen = false;
  $scope.toggleDropdown = function() {
    return $scope.dropdownOpen = !$scope.dropdownOpen;
  };
  $scope.support = function() {
    return alert(1);
  };
  $scope.arrowNav = {};
  return $scope.$watch("page", function() {
    switch ($scope.page) {
      case "home":
        return $scope.arrowNav = {
          left: 23,
          hide: false
        };
      case "msg":
        return $scope.arrowNav = {
          left: 90,
          hide: false
        };
      case "me":
        return $scope.arrowNav = {
          left: 176,
          hide: false
        };
      case "friend":
        return $scope.arrowNav = {
          left: 260,
          hide: false
        };
      default:
        return $scope.arrowNav = {
          left: 0,
          hide: true
        };
    }
  });
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("homeCtrl", [
  "$scope", "$routeParams", function($scope, $routeParams) {
    $scope.legalFeedTypes = ["news", "answer", "reply"];
    if (0 > $scope.legalFeedTypes.indexOf($routeParams.type)) {
      $routeParams.type = "news";
    }
    $scope.feedType = $routeParams.type;
    $scope.$on("$viewContentLoaded", function() {
      return $scope.$emit("pageChange", "home");
    });
    $scope.remind = {
      newsNum: 0,
      answerNum: 2,
      replyNum: '...'
    };
    $scope.$on("clearAnswerRemind", function() {
      return $scope.remind.answerNum = 0;
    });
    $scope.$on("clearReplyRemind", function() {
      return $scope.remind.replyNum = 0;
    });
    $scope.loadingMore = function() {
      return $scope.isLoading = true;
    };
    return false;
  }
]);

// Generated by CoffeeScript 1.7.1
Mifan.controller("homeAnswer", function($scope) {
  $scope.content = "回答我的";
  console.log("回答我的");
  return $scope.$emit("clearAnswerRemind");
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("homeAskCtrl", function($scope) {
  $scope.askQuesConent = "";
  $scope.bgUrl = "images/ask-bg-2.jpg";
  $scope.avatarUrl = "http://tp4.sinaimg.cn/2005321383/180/5698650002/1";
  $scope.isSending = false;
  $scope.onFocus = function() {
    return $scope.onInputing = true;
  };
  $scope.onBlur = function(force) {
    if (force || $scope.askQuesConent === "") {
      return $scope.onInputing = false;
    }
  };
  return $scope.send = function() {
    return $scope.isSending = true;
  };
});

// Generated by CoffeeScript 1.7.1
Mifan.controller("homeNews", function($scope) {
  $scope.content = "最新动态";
  console.log("最新动态");
  return $scope.newsCollect = [
    {
      a: 1
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }, {
      a: 2
    }
  ];
});

// Generated by CoffeeScript 1.7.1
Mifan.controller("homeReply", function($scope) {
  $scope.content = "回应我的";
  console.log("回应我的");
  return $scope.$emit("clearReplyRemind");
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("homeSideCtrl", function($scope) {
  return $scope.mifanAskContent = "情人节和谁过的？";
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("loginCtrl", function($scope, $http, $cookieStore, $timeout) {
  var API, IsDebug, LOC, userLogin, userLoginErrorCb, userLoginSuccessCb;
  API = $scope.API;
  IsDebug = $scope.IsDebug;
  LOC = $scope.LOC;
  $scope.error = null;
  userLoginSuccessCb = function(data, status) {

    /*
    {
      "msg": "密码错误！",
      "ret": "104003"
    }
    
    {
      "msg": "Email不存在，你可能还没有注册！",
      "ret": "104002"
    }
    
    {
      "msg": "OK",
      "ret": "100000",
      "result": {}
    }
     */
    var result, ret;
    ret = data["ret"];
    if (ret === "100000") {
      result = data["result"];
      $scope.$emit("onLogined", result);
      LOC["href"] = "#!/";
    } else if (ret === "104003") {
      $scope.error = {
        type: "password",
        msg: "密码错误 :("
      };
    } else if (ret === "104002") {
      $scope.error = {
        type: "username",
        msg: "用户名不存在 T_T"
      };
    }
    if ($scope.error) {
      $timeout(function() {
        return $scope.error = null;
      }, 3000);
    }
    return $scope.isLoging = false;
  };
  userLoginErrorCb = function(data, status) {
    var ret;
    ret = data["ret"];
    return $scope.isLoging = false;
  };
  userLogin = function() {
    $scope.isLoging = true;
    return $http({
      method: IsDebug ? "GET" : "POST",
      url: API.user,
      data: {
        user_email: $scope.email,
        user_password: $scope.password
      }
    }).success(userLoginSuccessCb).error(userLoginErrorCb);
  };
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "login");
  });
  $scope.$watch("email + password", function() {
    return $scope.isLogValid = $scope.email && $scope.password;
  });
  $scope.isLoging = false;
  return $scope.onSubmit = function() {
    if ($scope.email && $scope.password) {
      return userLogin();
    }
  };
});

// Generated by CoffeeScript 1.7.1
Mifan.controller("mMenuCtrl", function($scope) {});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("meCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "me");
  });
  return false;
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("msgCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "msg");
  });
  return false;
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("registerCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "register");
  });
  $scope.$watch("email + password", function() {
    return $scope.isRegValid = $scope.email && $scope.password;
  });
  $scope.isReging = false;
  return $scope.regSubmit = function() {
    return $scope.isReging = true;
  };
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("rootCtrl", function($scope, $cookieStore, $http) {
  var API, IsDebug, accessToken, getUserInfo, getUserInfoCb, getUserInfoErrorCb, setUserInfo, uid, username;
  API = $scope.API;
  IsDebug = $scope.IsDebug;
  $scope.page = "home";
  $scope.accessToken = $scope.UID = void 0;
  $scope.isLogin = false;
  $scope.$on("onLogined", function(detail, result) {
    var user;
    $scope.isLogin = true;
    $scope.accessToken = result["accesstoken"];
    user = result["user"];
    $scope.UID = user["userid"];
    setUserInfo(user);
    $scope.user.accessToken = accessToken;
    $cookieStore.put("mUID", user["userid"]);
    $cookieStore.put("mUsername", user["username"]);
    return $cookieStore.put("mAccessToken", $scope.accessToken);
  });
  setUserInfo = function(user) {
    $scope.user.username = user["username"] || "";
    $scope.user.email = user["email"] || "";
    $scope.user.face = user["face"] || "";
    $scope.user.face_60 = user["face_60"] || "";
    $scope.user.face_120 = user["face_120"] || "";
    $scope.user.sex = user["sex"] || "1";
    $scope.user.blog = user["blog"] || "";
    return $scope.user.uid = user["userid"] || "";
  };
  getUserInfo = function() {
    var url;
    url = ("" + API.userInfo) + (IsDebug ? "" : "/" + uid) + ("" + $scope.privacyParam);
    return $http.get(url).success(getUserInfoCb).error(getUserInfoErrorCb);
  };
  getUserInfoCb = function(data) {
    var ret, user;
    ret = data["ret"];
    if (ret === "100000") {
      user = data["result"];
      return setUserInfo(user);
    }
  };
  getUserInfoErrorCb = function(data) {};
  $scope.user = {};
  uid = $cookieStore.get("mUID");
  accessToken = $cookieStore.get("mAccessToken");
  username = $cookieStore.get("mUsername");
  if (uid && accessToken) {
    $scope.isLogin = true;
    $scope.user.uid = $scope.UID = uid;
    $scope.accessToken = accessToken;
    $scope.user.face_60 = $scope.user.face_120 = $scope.DEFAULT_FACE;
    $scope.user.username = username;
    $scope.privacyParam = "?access_token=" + accessToken + "&userid=" + uid;
    getUserInfo();
  }
  $scope.supportNum = "1万";
  $scope.$on("pageChange", function(e, msg) {
    return $scope.page = msg;
  });
  $scope.isMMenuOpen = false;
  $scope.toggleMMenu = function() {
    return $scope.isMMenuOpen = !$scope.isMMenuOpen;
  };
  return $scope.logout = function() {
    $scope.user = {};
    $cookieStore.remove("mUID");
    $cookieStore.remove("mAccessToken");
    return $scope.isLogin = false;
  };
});

// Generated by CoffeeScript 1.7.1
"use strict";
Mifan.controller("welcomeCtrl", [
  "$scope", function($scope) {
    $scope.$on("$viewContentLoaded", function() {
      return $scope.$emit("pageChange", "welcome");
    });
    $scope.$watch("email + password", function() {
      return $scope.isLoginValid = $scope.email && $scope.password;
    });
    $scope.isLoginBox = false;
    $scope.isLoging = false;
    $scope.isReging = false;
    $scope.toggleLogin = function() {
      return $scope.isLoginBox = !$scope.isLoginBox;
    };
    $scope.loginSubmit = function() {
      return $scope.isLoging = true;
    };
    $scope.regSubmit = function() {
      return $scope.isReging = true;
    };
    return false;
  }
]);
