// Generated by CoffeeScript 1.7.1
(function(window, angular) {
  var Storage, WIN, getStorage, storage;
  WIN = window;
  Storage = angular.module("binnng.storage", []);
  getStorage = function() {
    var e, _localStorage;
    _localStorage = void 0;
    try {
      _localStorage = WIN["localStorage"];
    } catch (_error) {
      e = _error;
      alert("localStorage is not supported");
    }
    getStorage = function() {
      return WIN["localStorage"];
    };
    return _localStorage;
  };
  storage = getStorage();
  return Storage.factory("$storage", function() {
    return {
      set: function(key, value) {
        if (storage) {
          return storage.setItem(key, value);
        }
      },
      get: function(key) {
        var value;
        if (storage) {
          return value = storage.getItem(key);
        }
      },
      clear: function(key) {
        var _results;
        if (storage) {
          if (key) {
            _results = [];
            for (key in storage) {
              if (0 === key.indexOf(key)) {
                _results.push(storage.removeItem(key));
              } else {
                _results.push(void 0);
              }
            }
            return _results;
          } else {
            return storage.clear();
          }
        }
      }
    };
  });
})(window, angular);
