// Generated by CoffeeScript 1.7.1
Mifan.controller("friendCtrl", function($scope) {
  $scope.$on("$viewContentLoaded", function() {
    return $scope.$emit("pageChange", "friend");
  });
  $scope.feedType = "follow";
  return $scope.switchFeed = function(type) {
    return $scope.feedType = type || "follow";
  };
});
