// Generated by CoffeeScript 1.7.1

/*
自定义标签
 */
Mifan.directive("more", function() {
  return {
    templateUrl: "views/template/more.html",
    replace: true,
    restrict: "E"
  };
});

Mifan.directive("snslogin", function() {
  return {
    templateUrl: "views/template/sns-login.html",
    replace: true,
    restrict: "E"
  };
});

Mifan.directive("usermenu", function() {
  return {
    priority: 0,
    templateUrl: "views/template/usermenu.html",
    replace: true,
    restrict: "E",
    scope: false
  };
});
