// Generated by CoffeeScript 1.7.1
Mifan.directive("expander", function() {
  return {
    restrict: "EA",
    scope: {},
    link: function(scope, element, attrs, ctrl) {
      return element.on("click", function() {});
    }
  };
});
