// Generated by CoffeeScript 1.7.1
(function(window, angular) {

  /*
  angualr 指令
  轮播器
  支持mobile and pc
   */
  'use strict';
  var DOC, END_EVENT, IsAndroid, IsTouch, MOVE_EVENT, START_EVENT, UA, UNDEFINED, WIN, ngScorller;
  DOC = document;
  WIN = window;
  UNDEFINED = void 0;
  IsTouch = 'ontouchstart' in WIN;
  UA = WIN.navigator.userAgent;
  IsAndroid = /Android|HTC/i.test(UA) || !!(WIN.navigator["platform"] + "").match(/Linux/i);
  START_EVENT = IsTouch ? 'touchstart' : 'mousedown';
  MOVE_EVENT = IsTouch ? 'touchmove' : 'mousemove';
  END_EVENT = IsTouch ? 'touchend' : 'mouseup';
  return ngScorller = angular.module("binnng.scroller", []);
})(window, angular);
