// Generated by CoffeeScript 1.7.1
Mifan.directive("subNav", function() {
  return {
    templateUrl: "views/template/sub-nav.html",
    replace: false,
    transclude: true,
    restrict: "AE",
    scope: {
      feedType: "=feedType"
    },
    link: function(scope, element, attrs) {},
    compile: function(element, attrs, transclude) {
      return {
        pre: function() {},
        post: function(scope, element, attrs, controller) {
          var ele, items, length, ul, _i, _len, _results;
          ul = element[0].getElementsByTagName("ul")[0];
          items = ul.getElementsByTagName("li");
          length = items.length;
          _results = [];
          for (_i = 0, _len = items.length; _i < _len; _i++) {
            ele = items[_i];
            _results.push(ele.style.width = "" + (100 / length) + "%");
          }
          return _results;
        }
      };
    }
  };
});
