// Generated by CoffeeScript 1.7.1
Mifan.directive("subNav", function() {
  return {
    templateUrl: "views/template/sub-nav.html",
    replace: false,
    transclude: true,
    restrict: "AE",
    scope: false
  };
});
